/* Shia App Factory — BORIS-001 build pass.
   Boris holds the BORIS-BUILD-001 grant, so he does not only review the graph: he compiles it into
   a runnable export — a shell page, the glue that routes records between the real block runtimes,
   and an executable check script for what he generated.

   Three rules shape this module, and all three are load-bearing:

   **He builds from the graph, never from intent.** Every route in the generated glue comes from a
   connection that exists in `project.connections`. Nothing is inferred, filled in or helpfully
   completed.

   **He refuses to build over a defect he can see.** If the advisory pass reports a high-severity
   structural finding, the build is BLOCKED and returns the blockers instead of an artifact. An
   export that quietly encodes a broken graph is worse than no export.

   **Building is not landing.** The grant withholds merge, deploy and secrets. This module writes
   files into a returned artifact list; it does not write to disk, does not touch the network, and
   has no code path to publishing anything. What happens to the export is Cristian's call.

   Output is deterministic: same graph in, byte-identical artifacts out. There are no timestamps
   and no randomness, so two builds of the same graph can be compared directly. */
(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root)root.ShiaAgentBuild=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){

/* Which directory under blocks/ serves each block type. The Factory hardcodes this pairing in its
   preview; the build takes it as an option so a renamed runtime does not silently break the export. */
const DEFAULT_RUNTIMES={forms:'forms-001',records:'records-002'};

/* Build targets. They differ in what gets emitted, not in how the graph is read. */
const TARGETS={
  'export':{label:'Runnable Export',artifacts:['shia-app.html','glue.js','checks.mjs','README.md','build-manifest.json']},
  'glue':{label:'Glue Only',artifacts:['glue.js','checks.mjs']},
  'checks':{label:'Checks Only',artifacts:['checks.mjs']}
};

/* FNV-1a, 32-bit. Enough to tell two graphs apart in a manifest, and identical in Node and the
   browser without pulling in a crypto dependency. It is a change detector, not a security digest. */
function fingerprint(s){
  let h=0x811c9dc5;
  for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,0x01000193)>>>0}
  return ('0000000'+h.toString(16)).slice(-8);
}

const j=v=>JSON.stringify(v,null,2);
const jsString=s=>JSON.stringify(String(s));
const bytes=s=>{
  if(typeof TextEncoder!=='undefined')return new TextEncoder().encode(s).length;
  return Buffer.byteLength(s,'utf8');
};

/* The graph as the build sees it: ids, types, titles and routes, with nothing else along for the
   ride. Coordinates and selection state are deliberately dropped so moving a block on the canvas
   does not change the fingerprint of what gets built. */
function normalize(project,runtimes){
  const blocks=((project&&project.blocks)||[]).map(b=>({
    id:b.id,
    type:b.type,
    title:b.title||b.id,
    runtime:runtimes[b.type]||b.type
  })).sort((a,b)=>a.id<b.id?-1:a.id>b.id?1:0);
  const known=new Set(blocks.map(b=>b.id));
  const routes=((project&&project.connections)||[])
    .filter(c=>known.has(c.from)&&known.has(c.to))
    .map(c=>({from:c.from,fromPort:c.fromPort,to:c.to,toPort:c.toPort,type:c.type}))
    .sort((a,b)=>{
      const ka=`${a.from}.${a.fromPort}->${a.to}.${a.toPort}`,kb=`${b.from}.${b.fromPort}->${b.to}.${b.toPort}`;
      return ka<kb?-1:ka>kb?1:0;
    });
  return {name:(project&&project.name)||'Untitled Shia App',blocks,routes};
}

/* ---------------------------------------------------------------- generated glue */

function generateGlue(graph,opts){
  const base=opts.blocksBase.replace(/\/+$/,'');
  return `/* GENERATED by BORIS-001 from the Shia App Factory graph "${graph.name}".
   Graph fingerprint: ${graph.fingerprint}
   Regenerate rather than hand-edit: the checks in checks.mjs verify this file against the graph.

   This implements the same runtime contract the Factory uses.

     block  -> parent : {source:'shia-block-runtime', type:'ready',       instanceId}
                        {source:'shia-block-runtime', type:'port-output', instanceId, port, dataType, payload}
                        {source:'shia-block-runtime', type:'ack',         instanceId, deliveryId, port}
     parent -> block  : {source:'shia-factory',       type:'configure',   instanceId, config}
                        {source:'shia-factory',       type:'port-input',  instanceId, port, dataType, payload, fromInstanceId, deliveryId}

   One detail worth keeping: the forms runtime re-announces 'ready' after it is configured. Each
   instance is therefore configured exactly once — configuring on every ready is what turns that
   into a handshake loop. */
(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root)root.ShiaGlue=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){

const BLOCKS=${j(graph.blocks)};

const ROUTES=${j(graph.routes)};

const BLOCKS_BASE=${jsString(base)};
const CONFIGURATION=${jsString(opts.configuration)};

function srcFor(block){
  return BLOCKS_BASE+'/'+block.runtime+'/index.html?instance='+encodeURIComponent(block.id);
}

/* Routes leaving one instance on one port. Built from the graph, so an output with no destination
   stays undelivered and says so, rather than being quietly dropped. */
function routesFrom(instanceId,port,dataType){
  return ROUTES.filter(r=>r.from===instanceId&&r.fromPort===port&&r.type===dataType);
}

function mount(stage,options){
  const opts=options||{};
  const log=typeof opts.log==='function'?opts.log:()=>{};
  const frames=new Map();
  const configured=new Set();
  const pending=new Map();
  let deliverySeq=0;

  BLOCKS.forEach(b=>{
    const shell=document.createElement('section');
    shell.className='runtime-shell';
    const label=document.createElement('div');
    label.className='runtime-label';
    label.innerHTML='<b></b><span class="runtime-state"></span>';
    label.querySelector('b').textContent=b.title;
    label.querySelector('.runtime-state').textContent='Loading '+b.runtime+'…';
    label.querySelector('.runtime-state').id='state-'+b.id;
    const frame=document.createElement('iframe');
    frame.className='runtime-frame';
    frame.title=b.title;
    frame.src=srcFor(b);
    shell.append(label,frame);
    stage.appendChild(shell);
    frames.set(b.id,frame);
  });

  function state(id,text){
    const el=document.getElementById('state-'+id);
    if(el)el.textContent=text;
  }

  function onMessage(event){
    const msg=event.data;
    if(!msg||msg.source!=='shia-block-runtime')return;
    const block=BLOCKS.find(b=>b.id===msg.instanceId);

    if(msg.type==='ready'){
      state(msg.instanceId,'Ready');
      /* Configure once. The forms runtime replies to configure with another ready. */
      if(configured.has(msg.instanceId))return;
      configured.add(msg.instanceId);
      const frame=frames.get(msg.instanceId);
      if(block&&frame&&frame.contentWindow){
        frame.contentWindow.postMessage({source:'shia-factory',type:'configure',instanceId:block.id,
          config:{title:block.title,configuration:CONFIGURATION}},'*');
      }
      log((block?block.title:msg.instanceId)+' runtime ready');
      return;
    }

    if(msg.type==='port-output'){
      const targets=routesFrom(msg.instanceId,msg.port,msg.dataType);
      if(!targets.length){
        log('No route for '+(block?block.title:msg.instanceId)+'.'+msg.port+' — record not delivered');
        return;
      }
      targets.forEach(route=>{
        const frame=frames.get(route.to);
        if(!frame||!frame.contentWindow){
          log('Runtime unavailable for '+route.to+' — delivery failed');
          return;
        }
        const deliveryId='delivery-'+(++deliverySeq);
        pending.set(deliveryId,route);
        frame.contentWindow.postMessage({source:'shia-factory',type:'port-input',instanceId:route.to,
          port:route.toPort,dataType:route.type,payload:msg.payload,fromInstanceId:msg.instanceId,deliveryId},'*');
      });
      return;
    }

    if(msg.type==='ack'){
      /* An unknown deliveryId means an acknowledgement arrived for something never sent —
         reported rather than ignored. */
      if(!pending.has(msg.deliveryId)){
        log('Unmatched acknowledgement '+msg.deliveryId);
        return;
      }
      pending.delete(msg.deliveryId);
      log((block?block.title:msg.instanceId)+' acknowledged '+msg.port);
    }
  }

  window.addEventListener('message',onMessage);

  return {
    blocks:BLOCKS,
    routes:ROUTES,
    frames,
    /* Deliveries still waiting on an ack. A non-empty set after a run is a real defect. */
    pending,
    unmount(){window.removeEventListener('message',onMessage)}
  };
}

return {BLOCKS,ROUTES,BLOCKS_BASE,CONFIGURATION,srcFor,routesFrom,mount,FINGERPRINT:${jsString(graph.fingerprint)}};
});
`;
}

/* ---------------------------------------------------------------- generated shell */

function generateHtml(graph){
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(graph.name)}</title>
<!-- GENERATED by BORIS-001. Graph fingerprint: ${graph.fingerprint} -->
<style>
:root{color-scheme:light dark}
*{box-sizing:border-box}
body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;background:#f3f5fa;color:#172033}
@media(prefers-color-scheme:dark){body{background:#070b14;color:#eef2ff}}
header{display:flex;gap:12px;align-items:center;padding:12px 16px;background:#080d17;color:#fff}
header strong{letter-spacing:.03em}
header .tag{font-size:12px;color:#c8cfe0;border:1px solid #343e57;border-radius:999px;padding:4px 8px}
main{max-width:1500px;margin:auto;padding:20px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;align-items:start}
.runtime-shell{min-width:0}
.runtime-label{display:flex;justify-content:space-between;gap:10px;align-items:center;margin:0 0 8px;font-size:13px}
.runtime-state{opacity:.65}
.runtime-frame{width:100%;height:980px;border:1px solid #d9deea;border-radius:15px;background:#fff}
#log{background:#101522;color:#e5e7eb;padding:10px 14px;max-height:170px;overflow:auto;font:12px ui-monospace,monospace}
@media(max-width:900px){main{grid-template-columns:1fr}.runtime-frame{height:1050px}}
</style>
</head>
<body>
<header><strong>${esc(graph.name)}</strong><span class="tag">${graph.blocks.length} block${graph.blocks.length===1?'':'s'}</span><span class="tag">${graph.routes.length} route${graph.routes.length===1?'':'s'}</span><span class="tag">graph ${graph.fingerprint}</span></header>
<main id="stage"></main>
<div id="log"></div>
<script src="glue.js"><\/script>
<script>
(()=>{
  const log=document.getElementById('log');
  ShiaGlue.mount(document.getElementById('stage'),{log(line){
    const row=document.createElement('div');
    row.textContent=new Date().toLocaleTimeString()+'  '+line;
    log.appendChild(row);log.scrollTop=log.scrollHeight;
  }});
})();
<\/script>
</body>
</html>
`;
}

/* ---------------------------------------------------------------- generated checks */

function generateChecks(graph){
  return `/* GENERATED by BORIS-001 for the graph "${graph.name}" (fingerprint ${graph.fingerprint}).
   Run with:  node checks.mjs
   These verify the generated glue against the graph it was generated from. They exercise the
   routing table without a DOM; they do not claim the mounted runtimes behave correctly, which
   only a real run in a browser can show. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';

const require=createRequire(import.meta.url);
const glue=require('./glue.js');

const EXPECTED_BLOCKS=${j(graph.blocks)};

const EXPECTED_ROUTES=${j(graph.routes)};

test('the glue was generated from this graph', () => {
  assert.equal(glue.FINGERPRINT, ${jsString(graph.fingerprint)});
});

test('every block in the graph is mounted, and no others', () => {
  assert.deepEqual(glue.BLOCKS, EXPECTED_BLOCKS);
});

test('every route in the graph is routed, and no others', () => {
  assert.deepEqual(glue.ROUTES, EXPECTED_ROUTES);
});

test('each block resolves to a runtime under the blocks base', () => {
  for(const b of glue.BLOCKS){
    const src=glue.srcFor(b);
    assert.ok(src.startsWith(glue.BLOCKS_BASE+'/'+b.runtime+'/'), \`block \${b.id} resolves outside its runtime: \${src}\`);
    assert.ok(src.includes('instance='+encodeURIComponent(b.id)), \`block \${b.id} is mounted without its instance id\`);
  }
});

test('no route leaves or enters a block that is not mounted', () => {
  const ids=new Set(glue.BLOCKS.map(b=>b.id));
  for(const r of glue.ROUTES){
    assert.ok(ids.has(r.from), \`route from an unmounted block: \${r.from}\`);
    assert.ok(ids.has(r.to), \`route into an unmounted block: \${r.to}\`);
    assert.notEqual(r.from, r.to, \`block routes to itself: \${r.from}\`);
  }
});

test('routesFrom returns exactly the routes leaving a port', () => {
  for(const r of glue.ROUTES){
    const found=glue.routesFrom(r.from, r.fromPort, r.type);
    assert.ok(found.some(x=>x.to===r.to&&x.toPort===r.toPort), \`\${r.from}.\${r.fromPort} does not route to \${r.to}.\${r.toPort}\`);
  }
  assert.deepEqual(glue.routesFrom('no-such-block','submitted','Record'), []);
});
`;
}

/* ---------------------------------------------------------------- generated readme */

function generateReadme(graph,opts,checks){
  const routeLines=graph.routes.length
    ? graph.routes.map(r=>`| \`${r.from}.${r.fromPort}\` | \`${r.to}.${r.toPort}\` | ${r.type} |`).join('\n')
    : '| — | — | no routes in this graph |';
  const blockLines=graph.blocks.map(b=>`| ${b.title} | \`${b.id}\` | \`blocks/${b.runtime}/\` |`).join('\n');
  return `# ${graph.name}

Generated by **BORIS-001** from the Shia App Factory graph \`${graph.fingerprint}\`.
Boris holds the \`BORIS-BUILD-001\` grant, which lets him author code inside the Factory.

## What this is

A runnable export of the graph: the block runtimes mounted side by side, with generated glue
wiring their ports together over the Factory's \`postMessage\` contract.

| Block | Instance | Runtime |
| --- | --- | --- |
${blockLines}

| From | To | Type |
| --- | --- | --- |
${routeLines}

## Running it

Place \`shia-app.html\`, \`glue.js\` and \`checks.mjs\` where \`${opts.blocksBase}\` resolves to the
Factory's block directory — the Factory root is the obvious spot — then serve the directory and
open \`shia-app.html\`. The runtimes are iframes talking over \`postMessage\`, so \`file://\` will not
do; any static server will.

\`\`\`sh
python3 -m http.server 8080
# then open http://localhost:8080/shia-app.html
\`\`\`

## Checking it

\`\`\`sh
node --test checks.mjs
\`\`\`

${checks.length} check${checks.length===1?'':'s'} verify the generated glue against the graph it came
from: the mounted blocks, the routing table, runtime resolution, and that no route touches a block
that is not mounted. They are static checks over the generated code. They do not claim the mounted
runtimes behave correctly — only a real run in a browser shows that.

## What Boris did not do

The build grant withholds three things, and they are withheld here too:

- **Merging** — this export is not landed anywhere.
- **Deploying** — nothing was published, uploaded or released.
- **Secrets** — no credential, key or \`.env\` was read, and the generated code contains none.

Final authority: **Cristian**.

## Regenerating

Edit the graph in the Factory and build again. Hand-edits to \`glue.js\` are overwritten on the next
build, and \`checks.mjs\` fails if the glue stops matching its graph.
`;
}

/* ---------------------------------------------------------------- the pass */

function checksFor(graph){
  const out=[
    {id:'glue-provenance',name:'The glue was generated from this graph',expect:`fingerprint ${graph.fingerprint}`},
    {id:'blocks-mounted',name:'Every block is mounted, and no others',expect:`${graph.blocks.length} block${graph.blocks.length===1?'':'s'}`},
    {id:'routes-wired',name:'Every route is wired, and no others',expect:`${graph.routes.length} route${graph.routes.length===1?'':'s'}`},
    {id:'runtime-resolution',name:'Each block resolves to a runtime under the blocks base',expect:'no path escapes its runtime directory'},
    {id:'no-orphan-routes',name:'No route touches an unmounted block, and none is a self-route',expect:'every endpoint is mounted'},
    {id:'route-lookup',name:'routesFrom returns exactly the routes leaving a port',expect:'unknown ports return no routes'}
  ];
  return out;
}

function build(project,options){
  const opts=options||{};
  const runtimes=Object.assign({},DEFAULT_RUNTIMES,opts.runtimes||{});
  const targetId=TARGETS[opts.target]?opts.target:'export';
  const target=TARGETS[targetId];
  const blocksBase=opts.blocksBase||'blocks';
  const configuration=opts.configuration||'barber';

  const graph=normalize(project,runtimes);
  graph.fingerprint=fingerprint(JSON.stringify({name:graph.name,blocks:graph.blocks,routes:graph.routes}));

  const notes=[
    'Boris authored this under grant BORIS-BUILD-001. The grant withholds merge, deploy and secrets — building is not landing.',
    'Output is deterministic: the same graph produces byte-identical artifacts.',
    'Runtime recertification is PENDING — this host is not certified as Boris.'
  ];

  const base={agent_id:'BORIS-001',target:targetId,target_label:target.label,graph:{
    name:graph.name,blocks:graph.blocks.length,routes:graph.routes.length,fingerprint:graph.fingerprint}};

  if(!graph.blocks.length){
    return Object.assign({},base,{status:'empty',artifacts:[],checks:[],blockers:[],
      summary:'Nothing to build — the workbench is empty.',notes});
  }

  /* Boris will not compile a graph he has just found a high-severity defect in. The blockers are
     returned as they were reported, so the same finding that stops the build is the one shown. */
  let blockers=[];
  if(opts.advisory&&typeof opts.advisory.review==='function'){
    let review=null;
    try{
      review=opts.advisory.review(project,{defs:opts.defs,scope:'factory',telemetry:opts.telemetry});
    }catch(e){
      return Object.assign({},base,{status:'error',artifacts:[],checks:[],blockers:[],
        error:`The pre-build review did not complete: ${e&&e.message?e.message:'unknown error'}`,
        summary:'Build abandoned — the pre-build review failed, so the graph was never verified.',notes});
    }
    blockers=((review&&review.findings)||[]).filter(f=>f.severity==='high');
  }
  if(blockers.length&&!opts.force){
    return Object.assign({},base,{status:'blocked',artifacts:[],checks:[],blockers,
      summary:`Build blocked — ${blockers.length} high-severity defect${blockers.length===1?'':'s'} in the graph. Fix ${blockers.length===1?'it':'them'}, or build again with Force.`,
      notes:notes.concat('An export that encodes a known-broken graph is worse than no export.')});
  }

  const checks=checksFor(graph);
  const files={
    'glue.js':{language:'javascript',contents:generateGlue(graph,{blocksBase,configuration})},
    'shia-app.html':{language:'html',contents:generateHtml(graph)},
    'checks.mjs':{language:'javascript',contents:generateChecks(graph)},
    'README.md':{language:'markdown',contents:generateReadme(graph,{blocksBase},checks)},
    'build-manifest.json':{language:'json',contents:''}
  };

  const emitted=target.artifacts.filter(p=>p!=='build-manifest.json');
  const artifacts=emitted.map(path=>({
    path,language:files[path].language,contents:files[path].contents,
    bytes:bytes(files[path].contents),fingerprint:fingerprint(files[path].contents)
  }));

  if(target.artifacts.includes('build-manifest.json')){
    const manifest={
      generated_by:'BORIS-001',
      grant:'BORIS-BUILD-001',
      target:targetId,
      graph:{name:graph.name,fingerprint:graph.fingerprint,blocks:graph.blocks,routes:graph.routes},
      blocks_base:blocksBase,
      artifacts:artifacts.map(a=>({path:a.path,bytes:a.bytes,fingerprint:a.fingerprint})),
      checks:checks.map(c=>c.id),
      withheld:['may_merge','may_deploy','may_access_secrets'],
      final_authority:'Cristian'
    };
    const contents=j(manifest)+'\n';
    artifacts.push({path:'build-manifest.json',language:'json',contents,
      bytes:bytes(contents),fingerprint:fingerprint(contents)});
  }

  const built=blockers.length
    ? `Built over ${blockers.length} high-severity defect${blockers.length===1?'':'s'} because Force was set — the export encodes a graph Boris flagged.`
    : `Built ${artifacts.length} artifact${artifacts.length===1?'':'s'} from ${graph.blocks.length} block${graph.blocks.length===1?'':'s'} and ${graph.routes.length} route${graph.routes.length===1?'':'s'}.`;

  return Object.assign({},base,{
    status:'built',
    artifacts,
    checks,
    blockers,
    forced:Boolean(blockers.length&&opts.force),
    summary:built,
    notes
  });
}

return {build,normalize,fingerprint,TARGETS,DEFAULT_RUNTIMES};
});
