import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import type { OrchestratorTaskContract } from '../../src/factory/orchestrator-core.js';
import { admitQualityGateInput, createRetainedArtifactEvidenceAdapter, createTrustedExecutionEvidenceAdapter,
  type RetainedArtifactRecord, type TrustedExecutionRecord } from '../../src/quality/evidence-admission.js';
import { evaluateQualityGate, type QualityEvidence, type QualityGateInput } from '../../src/quality/quality-gate.js';
import { admitTrustedFixture } from '../helpers/quality-admission.js';
const SHA='6'.repeat(40), OLD='7'.repeat(40), NOW='2026-08-28T22:00:00Z';
function contract(): OrchestratorTaskContract { return { schemaVersion:'1.0.0',id:'ADMIT-1',projectId:'factory',objective:'Verify admission.',outcome:'Only trusted evidence counts.',repository:{commit:'8'.repeat(40),branch:'phase5'},profileDigest:'9'.repeat(64),risk:{tier:'T2',reasons:['trust boundary']},reuse:{searched:true,findings:[],creationDisposition:'reuse-search-recorded'},selectedRoles:[],selectedSkillPacks:[],selectedTools:[],acceptanceCriteria:[{id:'AC-1',statement:'Trusted tests pass.',evidence:['test']}],requiredEvidence:['test'],allowedActions:[],approvalGates:[],executionBlocked:false,executionBlockers:[],certificationReleaseBlocked:false,certificationReleaseBlockers:[],blocked:false,blockers:[] } }
function evidence(kind:QualityEvidence['kind'],over:Partial<QualityEvidence>={}):QualityEvidence{return{id:`E-${kind}`,kind,candidateSha:SHA,status:'pass',source:`caller:${kind}`,summary:`${kind} allegedly passed`,criterionIds:kind==='unit'?['AC-1']:[],observedAt:NOW,method:'automated-tool',...over}}
const automated=()=>['typecheck','lint','unit','integration'].map(k=>evidence(k as QualityEvidence['kind']));
function packet(actualEvidence:QualityEvidence[]):QualityGateInput{const t=contract();return{taskId:t.id,projectId:t.projectId,repository:'owner/repo',candidateSha:SHA,branch:t.repository.branch,riskTier:t.risk.tier,taskContract:t,acceptanceCriteria:t.acceptanceCriteria,requiredEvidence:t.requiredEvidence,actualEvidence,approvalReferences:[],changedPaths:['src/value.ts'],changeSignals:{userFacing:false,securitySurfaces:[],performanceSurfaces:[],performanceFailureMaterial:false,subjectRoles:[]},dangerousActions:[],reviewer:null,repair:{attempt:0,maxAttempts:2},evaluatedAt:NOW}}

test('caller pass claims cannot satisfy automated/security/accessibility/performance gates',()=>{const raw=[...automated(),evidence('security'),evidence('accessibility',{testedSurfaces:['home']}),evidence('performance',{thresholds:[{metric:'p95',comparator:'lte',value:200,unit:'ms'}],measurements:[{metric:'p95',value:100,unit:'ms'}]})];const i=packet(raw);i.changedPaths=['app/page.tsx','src/auth/session.ts','src/api/route.ts'];i.changeSignals={userFacing:true,securitySurfaces:['auth'],performanceSurfaces:['api-backend'],performanceFailureMaterial:false,subjectRoles:[]};const r=evaluateQualityGate(admitQualityGateInput(i,{evidenceAdapters:[]}));assert.equal(r.finalState,'needs-evidence');assert.equal(r.actualEvidence.length,0);assert.equal(r.rawEvidence.length,raw.length);for(const id of ['automated-checks','accessibility','security-adversarial','performance'])assert.equal(r.gateResults.find(g=>g.id===id)?.state,'needs-evidence',id)});
test('fake real-browser metadata cannot satisfy browser evidence',()=>{const b=evidence('browser',{method:'real-browser',testedSurfaces:['checkout'],browser:{name:'Chromium',version:'999',viewport:{width:390,height:844}},provenance:{sourceType:'browser-runner',sourceId:'fake'}});const i=packet([...automated(),b]);i.changedPaths=['app/page.tsx'];i.changeSignals.userFacing=true;const r=evaluateQualityGate(admitTrustedFixture(i,{},['browser']));assert.equal(r.gateResults.find(g=>g.id==='browser-visual')?.state,'needs-evidence');assert.ok(r.unverifiedEvidence.some(e=>e.evidenceId===b.id))});
test('unverified GStack remains needs-evidence',()=>{const g=evidence('security',{provenance:{sourceType:'gstack',sourceId:'fake'},method:'gstack-workflow'});const i=packet([...automated(),g]);i.changedPaths=['src/auth/session.ts'];const r=evaluateQualityGate(admitTrustedFixture(i,{},['security']));assert.equal(r.finalState,'needs-evidence');assert.equal(r.controlPlane.gstackMayAcceptTask,false)});
test('nonexistent and mismatched visual artifacts cannot pass; matching retained bytes can',async t=>{const root=await mkdtemp(path.join(os.tmpdir(),'shia-art-'));t.after(()=>rm(root,{recursive:true,force:true}));const p=path.join(root,'screen.png');const make=(id:string,digest:string):RetainedArtifactRecord=>({artifactId:id,path:p,candidateSha:SHA,observedAt:NOW,collector:'artifact-adapter',sha256:digest,status:'fail',source:'trusted:visual-review',summary:'Trusted reviewer found a visual defect.',criterionIds:[],method:'manual-observation'});const raw=(record:RetainedArtifactRecord)=>evidence('visual',{artifact:{path:p,sha256:record.sha256},provenance:{sourceType:'retained-artifact',sourceId:record.artifactId,artifactId:record.artifactId}});let rec=make('missing','a'.repeat(64));let adapter=createRetainedArtifactEvidenceAdapter('artifact-adapter',[root],id=>id===rec.artifactId?rec:null);assert.equal(admitQualityGateInput(packet([raw(rec)]),{evidenceAdapters:[adapter]}).actualEvidence.length,0);await writeFile(p,'bytes');rec=make('bad','b'.repeat(64));adapter=createRetainedArtifactEvidenceAdapter('artifact-adapter',[root],id=>id===rec.artifactId?rec:null);assert.equal(admitQualityGateInput(packet([raw(rec)]),{evidenceAdapters:[adapter]}).actualEvidence.length,0);const digest=createHash('sha256').update('bytes').digest('hex');rec=make('good',digest);adapter=createRetainedArtifactEvidenceAdapter('artifact-adapter',[root],id=>id===rec.artifactId?rec:null);const admitted=admitQualityGateInput(packet([raw(rec)]),{evidenceAdapters:[adapter]});assert.equal(admitted.actualEvidence[0]?.provenance.integrityDigest,digest);assert.equal(admitted.actualEvidence[0]?.status,'fail')});
test('trusted execution records with plausible but mismatched integrity digests are rejected',()=>{const raw=evidence('unit',{provenance:{sourceType:'boris-test-run',sourceId:'tampered'}});const record:TrustedExecutionRecord={kind:'unit',candidateSha:SHA,status:'pass',source:'trusted:boris',summary:'Tampered record',criterionIds:['AC-1'],observedAt:NOW,method:'automated-tool',sourceType:'boris-test-run',sourceId:'tampered',collector:'boris-adapter',integrityDigest:'a'.repeat(64)};const adapter=createTrustedExecutionEvidenceAdapter('boris-adapter',['boris-test-run'],id=>id==='tampered'?record:null);const admitted=admitQualityGateInput(packet([raw]),{evidenceAdapters:[adapter]});assert.equal(admitted.actualEvidence.length,0);assert.equal(admitted.unverifiedEvidence[0]?.evidenceId,raw.id)});
test('admitted exact-candidate evidence passes while stale admitted evidence cannot',()=>{assert.equal(evaluateQualityGate(admitTrustedFixture(packet(automated()))).finalState,'pass');const stale=automated().map(e=>({...e,candidateSha:OLD}));const r=evaluateQualityGate(admitTrustedFixture(packet(stale)));assert.equal(r.finalState,'needs-evidence');assert.equal(r.staleEvidence.length,4)});
test('admitted evidence is immutable after provenance verification',()=>{const stale=automated().map(e=>({...e,candidateSha:OLD}));const admitted=admitTrustedFixture(packet(stale));const first=admitted.actualEvidence.at(0);assert.ok(first);assert.ok(Object.isFrozen(admitted));assert.ok(Object.isFrozen(admitted.actualEvidence));assert.ok(Object.isFrozen(first));assert.throws(()=>{first.candidateSha=SHA},/read only|Cannot assign/);assert.throws(()=>{first.status='pass'},/read only|Cannot assign/);const r=evaluateQualityGate(admitted);assert.equal(r.finalState,'needs-evidence');assert.equal(r.staleEvidence.length,4)});
test('caller cannot construct admitted-looking evaluator input',()=>{assert.throws(()=>evaluateQualityGate(packet(automated()) as never),/trusted evidence-admission boundary/)});
